module "dev_vm" {
  source                     = "../../modules/vm"
  environment                = "dev"
  mail_secret_key            = var.mail_secret_key
  mail_user                  = var.mail_user
  admin_username             = "adminuser"
  domain                     = var.domain
  resource_group             = "IN-RG-Diego"
  nic_name                   = "IN-NIC-Diego"
  mail_service               = var.mail_service
  mongo_url                  = var.mongo_url
  security_group_name        = "IN-SG-Diego"
  ssh_key_path               = "./keys/712_Incident_Server"
  port                       = var.port
  server_name                = "IN-Server-Diego"
  location                   = "eastus2"
  mapbox_access_token        = var.mapbox_access_token
  subnet_name                = "IN-SUBNET-Diego"
  mongo_initdb_root_username = var.mongo_initdb_root_username
  mongo_initdb_root_password = var.mongo_initdb_root_password
  mongo_db                   = var.mongo_db
  public_ip_name             = "IN-IP-Diego"
  vnet_name                  = "IN_VNET_Diego"
}